#### 1. Import pandas library

In [1]:
import pandas as pd

#### 2. Import pymysql and sqlalchemy as you have learnt in the lesson of importing/exporting data

In [2]:
import pymysql
import sqlalchemy

#### 3. Create a mysql engine to set the connection to the server. Check the connection details in [this link](https://relational.fit.cvut.cz/search?tableCount%5B%5D=0-10&tableCount%5B%5D=10-30&dataType%5B%5D=Numeric&databaseSize%5B%5D=KB&databaseSize%5B%5D=MB)

In [3]:
conn = pymysql.connect(
    host="relational.fit.cvut.cz",
    port=3306,
    user="guest",
    passwd= "relational",
    db="stats")

#### 4. Import the users table

In [4]:
users = pd.read_sql("SELECT * FROM users;", conn)

In [5]:
users.head()

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId,Age,ProfileImageUrl
0,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,1920,-1,NaN,None
1,2,101,2010-07-19 14:01:36,Geoff Dalgas,2013-11-12 22:07:23,http://stackoverflow.com,"Corvallis, OR",<p>Developer on the StackOverflow team. Find ...,25,3,0,2,37.0,None
2,3,101,2010-07-19 15:34:50,Jarrod Dixon,2014-08-08 06:42:58,http://stackoverflow.com,"New York, NY","<p><a href=""http://blog.stackoverflow.com/2009...",22,19,0,3,35.0,None
3,4,101,2010-07-19 19:03:27,Emmett,2014-01-02 09:31:02,http://minesweeperonline.com,"San Francisco, CA",<p>currently at a startup in SF</p>\n\n<p>form...,11,0,0,1998,28.0,http://i.stack.imgur.com/d1oHX.jpg
4,5,6792,2010-07-19 19:03:57,Shane,2014-08-13 00:23:47,http://www.statalgo.com,"New York, NY",<p>Quantitative researcher focusing on statist...,1145,662,5,54503,35.0,None

#### 5. Rename Id column to userId

In [6]:
users = users.rename(columns={"Id": "userId"})

users.head()

,userId,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,AccountId,Age,ProfileImageUrl
0,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,1920,-1,NaN,None
1,2,101,2010-07-19 14:01:36,Geoff Dalgas,2013-11-12 22:07:23,http://stackoverflow.com,"Corvallis, OR",<p>Developer on the StackOverflow team. Find ...,25,3,0,2,37.0,None
2,3,101,2010-07-19 15:34:50,Jarrod Dixon,2014-08-08 06:42:58,http://stackoverflow.com,"New York, NY","<p><a href=""http://blog.stackoverflow.com/2009...",22,19,0,3,35.0,None
3,4,101,2010-07-19 19:03:27,Emmett,2014-01-02 09:31:02,http://minesweeperonline.com,"San Francisco, CA",<p>currently at a startup in SF</p>\n\n<p>form...,11,0,0,1998,28.0,http://i.stack.imgur.com/d1oHX.jpg
4,5,6792,2010-07-19 19:03:57,Shane,2014-08-13 00:23:47,http://www.statalgo.com,"New York, NY",<p>Quantitative researcher focusing on statist...,1145,662,5,54503,35.0,None

#### 6. Import the posts table.

In [7]:
posts = pd.read_sql("SELECT * FROM posts;", conn)

In [8]:
posts.head(5)

,Id,PostTypeId,AcceptedAnswerId,CreaionDate,Score,ViewCount,Body,OwnerUserId,LasActivityDate,Title,...,AnswerCount,CommentCount,FavoriteCount,LastEditorUserId,LastEditDate,CommunityOwnedDate,ParentId,ClosedDate,OwnerDisplayName,LastEditorDisplayName
0,1,1,15.0,2010-07-19 19:12:12,23,1278.0,<p>How should I elicit prior distributions fro...,8.0,2010-09-15 21:08:26,Eliciting priors from experts,...,5.0,1,14.0,NaN,NaT,NaT,NaN,NaT,None,None
1,2,1,59.0,2010-07-19 19:12:57,22,8198.0,<p>In many different statistical methods there...,24.0,2012-11-12 09:21:54,What is normality?,...,7.0,1,8.0,88.0,2010-08-07 17:56:44,NaT,NaN,NaT,None,None
2,3,1,5.0,2010-07-19 19:13:28,54,3613.0,<p>What are some valuable Statistical Analysis...,18.0,2013-05-27 14:48:36,What are some valuable Statistical Analysis op...,...,19.0,4,36.0,183.0,2011-02-12 05:50:03,2010-07-19 19:13:28,NaN,NaT,None,None
3,4,1,135.0,2010-07-19 19:13:31,13,5224.0,<p>I have two groups of data. Each with a dif...,23.0,2010-09-08 03:00:19,Assessing the significance of differences in d...,...,5.0,2,2.0,NaN,NaT,NaT,NaN,NaT,None,None
4,5,2,NaN,2010-07-19 19:14:43,81,NaN,"<p>The R-project</p>\n\n<p><a href=""http://www...",23.0,2010-07-19 19:21:15,None,...,NaN,3,NaN,23.0,2010-07-19 19:21:15,2010-07-19 19:14:43,3.0,NaT,None,None

#### 7. Rename Id column to postId and OwnerUserId to userId

In [9]:
posts = posts.rename(columns={"Id": "postId", "OwnerUserId": "userId"})

In [10]:
posts.head(5)

,postId,PostTypeId,AcceptedAnswerId,CreaionDate,Score,ViewCount,Body,userId,LasActivityDate,Title,...,AnswerCount,CommentCount,FavoriteCount,LastEditorUserId,LastEditDate,CommunityOwnedDate,ParentId,ClosedDate,OwnerDisplayName,LastEditorDisplayName
0,1,1,15.0,2010-07-19 19:12:12,23,1278.0,<p>How should I elicit prior distributions fro...,8.0,2010-09-15 21:08:26,Eliciting priors from experts,...,5.0,1,14.0,NaN,NaT,NaT,NaN,NaT,None,None
1,2,1,59.0,2010-07-19 19:12:57,22,8198.0,<p>In many different statistical methods there...,24.0,2012-11-12 09:21:54,What is normality?,...,7.0,1,8.0,88.0,2010-08-07 17:56:44,NaT,NaN,NaT,None,None
2,3,1,5.0,2010-07-19 19:13:28,54,3613.0,<p>What are some valuable Statistical Analysis...,18.0,2013-05-27 14:48:36,What are some valuable Statistical Analysis op...,...,19.0,4,36.0,183.0,2011-02-12 05:50:03,2010-07-19 19:13:28,NaN,NaT,None,None
3,4,1,135.0,2010-07-19 19:13:31,13,5224.0,<p>I have two groups of data. Each with a dif...,23.0,2010-09-08 03:00:19,Assessing the significance of differences in d...,...,5.0,2,2.0,NaN,NaT,NaT,NaN,NaT,None,None
4,5,2,NaN,2010-07-19 19:14:43,81,NaN,"<p>The R-project</p>\n\n<p><a href=""http://www...",23.0,2010-07-19 19:21:15,None,...,NaN,3,NaN,23.0,2010-07-19 19:21:15,2010-07-19 19:14:43,3.0,NaT,None,None

#### 8. Define new dataframes for users and posts with the following selected columns:
    **users columns**: userId, Reputation,Views,UpVotes,DownVotes
    **posts columns**: postId, Score,userID,ViewCount,CommentCount

In [12]:
users_new = users[['userId', 'Reputation',"Views", "UpVotes", "DownVotes"]]
posts_new = posts[["postId", "Score", "userId", "ViewCount", "CommentCount"]]

#### 8. Merge both dataframes, users and posts. 
You will need to make a [merge](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) of posts and users dataframes.

In [21]:
users_posts = users.merge(right = posts, on="userId")

users_posts_new = users_new.merge(right =posts_new, on="userId")

#### 9. How many missing values do you have in your merged dataframe? On which columns?

In [22]:
# If considering users_new and posts_new, we have these results:

null_cols = users_posts_new.isnull().sum()
null_cols

userId              0
Reputation          0
Views               0
UpVotes             0
DownVotes           0
postId              0
Score               0
ViewCount       48396
CommentCount        0
dtype: int64

#### 10. You will need to make something with missing values.  Will you clean or filling them? Explain. 
**Remember** to check the results of your code before passing to the next step

** Answer: **

As these values are approximately half of the data frame, I would filling them. Maybe it will be useful to explore a little bit the data on that column and see what is the standard deviation of the data we have. If this value is too big, probably is not a good idea to fill the info. If not, we should fill the information with the mean of median of the data.

#### 11. Adjust the data types in order to avoid future issues. Which ones should be changed?

In [25]:
users_posts

,userId,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,...,AnswerCount,CommentCount,FavoriteCount,LastEditorUserId,LastEditDate,CommunityOwnedDate,ParentId,ClosedDate,OwnerDisplayName,LastEditorDisplayName
0,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2014-04-23 13:43:43,NaT,NaN,NaT,None,None
1,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-03-21 17:40:28,NaT,NaN,NaT,None,None
2,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-03-21 17:46:43,NaT,NaN,NaT,None,None
3,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,919.0,2011-03-30 19:23:14,NaT,NaN,NaT,None,None
4,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,919.0,2011-03-30 19:23:14,NaT,NaN,NaT,None,None
5,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-04-22 06:59:10,NaT,NaN,NaT,None,None
6,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,2116.0,2011-04-22 09:24:38,NaT,NaN,NaT,None,None
7,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-04-22 07:09:42,NaT,NaN,NaT,None,None
8,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-04-29 00:18:02,NaT,NaN,NaT,None,None
9,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-04-29 00:18:02,NaT,NaN,NaT,None,None
10,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2011-09-08 15:01:38,NaT,NaN,NaT,None,user5644
11,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2011-09-08 15:01:36,NaT,NaN,NaT,None,user5644
12,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,7290.0,2014-04-09 14:52:13,NaT,NaN,NaT,None,None
13,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-10-02 18:27:56,NaT,NaN,NaT,None,None
14,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-12-06 09:43:26,NaT,NaN,NaT,None,None
15,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-12-15 02:38:20,NaT,NaN,NaT,None,None
16,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2011-12-27 08:23:52,NaT,NaN,NaT,None,user7997
17,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2011-12-27 08:23:34,NaT,NaN,NaT,None,user7997
18,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2011-12-27 08:23:37,NaT,NaN,NaT,None,user7997
19,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2011-12-27 08:23:40,NaT,NaN,NaT,None,user7997
20,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2011-12-27 08:23:43,NaT,NaN,NaT,None,user7997
21,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2012-01-02 18:07:38,NaT,NaN,NaT,None,None
22,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2012-01-02 18:08:36,NaT,NaN,NaT,None,None
23,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2012-01-02 18:17:13,NaT,NaN,NaT,None,user7997
24,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,NaN,2012-01-02 18:17:10,NaT,NaN,NaT,None,user7997
25,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2012-01-22 15:04:34,NaT,NaN,NaT,None,None
26,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2012-01-27 01:25:07,NaT,NaN,NaT,None,None
27,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2012-01-28 09:37:15,NaT,NaN,NaT,None,None
28,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2012-01-28 09:46:15,NaT,NaN,NaT,None,None
29,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2012-01-28 09:46:15,NaT,NaN,NaT,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90554,55674,1,2014-09-12 10:18:00,user2975986,2014-09-13 01:24:10,None,None,None,0,0,...,1.0,1,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90555,55676,1,2014-09-12 10:46:27,Onkarabile,2014-09-12 10:46:27,None,None,None,1,0,...,1.0,1,NaN,36229.0,2014-09-12 21:30:20,NaT,NaN,2014-09-12 19:11:31,None,None
90556,55677,1,2014-09-12 10:47:26,nabby,2014-09-12 12:59:53,None,None,None,1,0,...,0.0,2,NaN,1739.0,2014-09-12 11:53:07,NaT,NaN,NaT,None,None
90557,55679,1,2014-09-12 11:20:58,Veronica,2014-09-13 06:07:07,None,None,None,0,0,...,0.0,0,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90558,55682,13,2014-09-12 12:10:03,user2329744,2014-09-13 19:35:31,None,None,None,0,0,...,1.0,0,NaN,28666.0,2014-09-12 13:56:08,NaT,NaN,NaT,None,None
90559,55684,6,2014-09-12 13:12:56,georgiar18,2014-09-12 15:13:06,None,None,None,0,0,...,0.0,6,NaN,55684.0,2014-09-12 13:59:04,NaT,NaN,NaT,None,None
90560,55687,6,2014-09-12 14:23:59,Barry,2014-09-12 14:45:36,None,None,None,0,0,...,1.0,0,NaN,7290.0,2014-09-12 18:49:11,NaT,NaN,NaT,None,None
90561,55689,6,2014-09-12 14:52:52,The Baron,2014-09-12 19:20:05,None,None,None,0,0,...,0.0,7,NaN,55689.0,2014-09-12 16:50:36,NaT,NaN,NaT,None,None
90562,55695,1,2014-09-12 16:01:07,Antonio Santos,2014-09-12 16:42:45,None,None,None,0,0,...,0.0,0,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90563,55697,1,2014-09-12 16:24:30,Edimbra,2014-09-13 09:42:26,None,None,None,0,0,...,0.0,4,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90564,55699,6,2014-09-12 17:26:43,failedstudent,2014-09-13 19:39:55,None,None,None,0,0,...,0.0,6,NaN,7290.0,2014-09-12 17:41:06,NaT,NaN,2014-09-12 19:15:03,None,None
90565,55702,26,2014-09-12 18:13:44,AMG,2014-09-12 18:13:44,None,None,None,1,0,...,0.0,1,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90566,55709,1,2014-09-12 22:21:49,Sam,2014-09-12 22:21:49,None,None,None,0,0,...,0.0,0,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90567,55710,1,2014-09-12 22:43:36,rmehta1987,2014-09-12 23:42:48,None,None,None,0,0,...,0.0,4,NaN,55710.0,2014-09-12 23:43:58,NaT,NaN,NaT,None,None
90568,55713,6,2014-09-13 00:01:13,Alex Spangher,2014-09-13 01:05:33,None,None,None,0,0,...,1.0,2,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90569,55714,6,2014-09-13 00:31:44,dean,2014-09-13 08:31:02,None,None,None,0,0,...,0.0,3,NaN,36229.0,2014-09-13 00:57:34,NaT,NaN,2014-09-13 19:29:33,None,None
90570,55715,6,2014-09-13 02:46:40,Alex,2014-09-13 02:46:40,None,None,None,0,0,...,1.0,0,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90571,55718,6,2014-09-13 07:12:49,Amena,2014-09-13 07:12:49,None,None,None,0,0,...,2.0,0,NaN,805.0,2014-09-13 08:00:04,NaT,NaN,2014-09-13 18:43:55,None,None
90572,55719,1,2014-09-13 07:19:09,OGUNNUSI OLUWATOBI,2014-09-13 08:03:19,None,None,None,1,0,...,0.0,0,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90573,55720,1,2014-09-13 08:00:08,Rebecca,2014-09-13 08:00:08,None,None,None,0,0,...,0.0,1,NaN,NaN,NaT,NaT,NaN,2014-09-13 10:39:03,None,None
90574,55724,16,2014-09-13 09:50:11,ouroboros,2014-09-13 10:05:17,None,None,<p>I'm a self-taught programmer and linux powe...,1,0,...,0.0,1,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90575,55729,16,2014-09-13 11:04:54,Achim Zeileis,2014-09-13 12:15:21,None,None,None,1,0,...,NaN,0,NaN,NaN,NaT,NaT,114959.0,NaT,None,None
90576,55730,1,2014-09-13 12:01:38,quants_mum,2014-09-13 12:01:38,None,None,None,0,0,...,0.0,1,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90577,55731,1,2014-09-13 15:23:34,Kiran BM,2014-09-13 20:51:55,None,None,None,0,0,...,0.0,0,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90578,55733,6,2014-09-13 15:51:18,Pax,2014-09-13 23:57:22,None,None,None,1,0,...,0.0,0,NaN,55733.0,2014-09-13 20:45:45,NaT,NaN,NaT,None,None
90579,55734,1,2014-09-13 15:56:55,jalen,2014-09-13 15:56:55,None,None,None,0,0,...,1.0,0,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90580,55738,11,2014-09-13 18:06:50,guest,2014-09-14 01:34:01,None,None,None,0,0,...,0.0,4,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90581,55742,6,2014-09-13 20:36:55,Sayan Ghosh,2014-09-13 22:04:00,None,None,None,0,0,...,1.0,0,1.0,NaN,NaT,NaT,NaN,NaT,None,None
90582,55744,6,2014-09-13 21:39:30,Mia Maria,2014-09-13 21:39:30,None,None,None,1,0,...,0.0,2,NaN,NaN,NaT,NaT,NaN,NaT,None,None
90583,55746,106,2014-09-14 00:29:41,GPP,2014-09-14 02:05:17,None,None,"<p>Stats noobie, product, marketing &amp; medi...",1,0,...,0.0,2,NaN,7290.0,2014-09-14 01:40:55,NaT,NaN,NaT,None,None

In [24]:
users_posts.head(5)

,userId,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,...,AnswerCount,CommentCount,FavoriteCount,LastEditorUserId,LastEditDate,CommunityOwnedDate,ParentId,ClosedDate,OwnerDisplayName,LastEditorDisplayName
0,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2014-04-23 13:43:43,NaT,NaN,NaT,None,None
1,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-03-21 17:40:28,NaT,NaN,NaT,None,None
2,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,-1.0,2011-03-21 17:46:43,NaT,NaN,NaT,None,None
3,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,919.0,2011-03-30 19:23:14,NaT,NaN,NaT,None,None
4,-1,1,2010-07-19 06:55:26,Community,2010-07-19 06:55:26,http://meta.stackexchange.com/,on the server farm,"<p>Hi, I'm not really a person.</p>\n\n<p>I'm ...",0,5007,...,NaN,0,NaN,919.0,2011-03-30 19:23:14,NaT,NaN,NaT,None,None

#### Bonus: Identify extreme values in your merged dataframe as you have learned in class, create a dataframe called outliers with the same columns as our data set and calculate the bounds. The values of the outliers dataframe will be the values of the merged_df that fall outside that bounds. You will need to save your outliers dataframe to a csv file on your-code folder.